name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'linux-system-') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Create Git tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/' + process.env.GITHUB_HEAD_REF,
              sha: context.sha
            })
