name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'linux-system-') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Create Git tag
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release/' + process.env.GITHUB_HEAD_REF,
              sha: context.sha
            })
