name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'gardena/release/') }}
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.tag.outputs.result }}
    steps:
      - name: Create Git tag
        id: tag
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          result-encoding: string
          script: |
            const branch = process.env.GITHUB_HEAD_REF
            const match = branch.match(/^gardena\/release\/(v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)$/)
            if (!match) {
              throw new Error(`${branch} does not contain a valid version`)
            }
            const tag = 'gardena/' + match[1]
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/' + tag,
              sha: context.sha
            })
            return tag

  # Creating a tag with GITHUB_TOKEN does not trigger a build, so call the workflow here for the tag
  build:
    needs: release
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yaml
    with:
      ref: refs/tags/${{ needs.release.outputs.tag }}
